#Your version: 0.6.0 Latest version: 0.6.0
# Generated by Neurodocker version 0.6.0
# Timestamp: 2020-03-03 17:43:28 UTC
# 
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:

# /app/main.sh -f test.nii.gz -j test.json -a mprage.nii.gz -o /out
#     https://github.com/kaczmarj/neurodocker

# docker build -f Dockerfile -t neurobox:latest . && docker run --name neurobox_test --rm neurobox:latest

#docker run -v /mnt/NAS/EMOATT/Dataset/sub-002/ses-day2/anat:/anat:ro -v /mnt/NAS/EMOATT/Dataset/sub-002/ses-day2/func/:/func:ro -v /mnt/NAS/workdir/docker_tests/out:/out -v /mnt/NAS/workdir/docker_tests/misc/:/dev/shm --name neurobox_test_run --pull missing neurobox:latest

FROM neurodebian:bionic-non-free

ARG DEBIAN_FRONTEND="noninteractive"

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker


RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           afni \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           ants \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV FSLDIR="/opt/fsl" \
    PATH="/opt/fsl/bin:$PATH" \
    FSLOUTPUTTYPE="NIFTI_GZ" \
    FSLMULTIFILEQUIT="TRUE" \
    FSLTCLSH="/opt/fsl/bin/fsltclsh" \
    FSLWISH="/opt/fsl/bin/fslwish" \
    FSLLOCKDIR="" \
    FSLMACHINELIST="" \
    FSLREMOTECALL="" \
    FSLGECUDAQ="cuda.q"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           ca-certificates \
           curl \
           dc \
           file \
           libfontconfig1 \
           libfreetype6 \
           libgl1-mesa-dev \
           libgl1-mesa-dri \
           libglu1-mesa-dev \
           libgomp1 \
           libice6 \
           libopenblas-base \
           libxcursor1 \
           libxft2 \
           libxinerama1 \
           libxrandr2 \
           libxrender1 \
           libxt6 \
           nano \
           python3 \
           sudo \
           wget \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Installing FSL ..." \
    && curl -fsSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/releases/fslinstaller.py | python3 - -d /opt/fsl -V 6.0.7.4 --extra truenet

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           convert3d \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           libtiff5 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           awscli \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5 /usr/lib/x86_64-linux-gnu/libtiff.so.3

    ADD ROBEXv12.linux64.tar.gz /

    ENV ANTSPATH="/usr/lib/ants"
    ENV PATH="/usr/lib/ants:.:${PATH}"
    ENV AWS_ACCESS_KEY_ID="AKIATU523SCUQEFJWBGW"
    ENV AWS_SECRET_ACCESS_KEY="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"

RUN apt-get update -qq && apt-get install -y jq \
                        && apt-get clean \
                        && rm -rf /var/lib/apt/lists/*

RUN curl -O --insecure https://afni.nimh.nih.gov/pub/dist/bin/misc/@update.afni.binaries
RUN ln -s /usr/lib/x86_64-linux-gnu/libgsl.so.23 /usr/lib/x86_64-linux-gnu/libgsl.so.19
RUN tcsh @update.afni.binaries -package linux_ubuntu_16_64 -do_extras -bindir /usr/local/AFNIbin

ENTRYPOINT ["/neurodocker/startup.sh"]

VOLUME /func
VOLUME /anat
VOLUME /final_out
VOLUME /out
VOLUME /dev/shm
VOLUME /fmap


WORKDIR /app
COPY functions /app/functions
COPY appdir_scripts/* /app
